// solo-meals.js — 30 solo-friendly recipe stubs (metadata only, no ingredients/method)
recipes.push(
    {
        id: 'solo-chicken-stir-fry',
        name: 'Quick Chicken Stir-Fry',
        image: '',
        cookTime: 15,
        calories: 420,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'quick', 'under-20-min', 'one-pan'],
        cuisine: 'chinese',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/quick-chicken-stir-fry' },
        favourite: false,
        timesCooked: 0,
        description: 'A fast weeknight stir-fry with chicken breast, pak choi and soy sauce. Ready in under 20 minutes.',
        dietary: ['dairy-free'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Chicken',
        prepTime: 5,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-chicken-caesar-salad',
        name: 'Chicken Caesar Salad for One',
        image: '',
        cookTime: 15,
        calories: 480,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'quick', 'low-carb', 'high-protein'],
        cuisine: 'american',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/chicken-caesar-salad' },
        favourite: false,
        timesCooked: 0,
        description: 'Pan-fried chicken on crisp romaine with homemade Caesar dressing and Parmesan shavings.',
        dietary: [],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Chicken',
        prepTime: 10,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-chicken-noodle-soup',
        name: 'Chicken Noodle Soup for One',
        image: '',
        cookTime: 20,
        calories: 350,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'comfort-food', 'one-pot', 'quick'],
        cuisine: 'british',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/chicken-noodle-soup-0' },
        favourite: false,
        timesCooked: 0,
        description: 'A warming bowl of chicken noodle soup. Perfect when you\'re feeling under the weather or just want something cosy.',
        dietary: ['dairy-free'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Chicken',
        prepTime: 5,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-teriyaki-chicken',
        name: 'Teriyaki Chicken with Rice',
        image: '',
        cookTime: 20,
        calories: 520,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'quick', 'fakeaway'],
        cuisine: 'japanese',
        source: { name: 'Mob Kitchen', url: 'https://www.mob.co.uk/recipes/teriyaki-chicken' },
        favourite: false,
        timesCooked: 0,
        description: 'Sticky teriyaki chicken thighs with steamed rice and quick pickled cucumber. Better than takeaway.',
        dietary: ['dairy-free'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Chicken',
        prepTime: 10,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-chicken-quesadilla',
        name: 'Chicken & Cheese Quesadilla',
        image: '',
        cookTime: 10,
        calories: 490,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'quick', 'under-20-min', 'budget-friendly'],
        cuisine: 'mexican',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/chicken-quesadilla' },
        favourite: false,
        timesCooked: 0,
        description: 'Crispy tortilla filled with leftover chicken, cheese and peppers. A 15-minute solo dinner classic.',
        dietary: [],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Chicken',
        prepTime: 5,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-cacio-e-pepe',
        name: 'Cacio e Pepe',
        image: '',
        cookTime: 12,
        calories: 450,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'quick', 'under-20-min', 'vegetarian', 'budget-friendly', '3-ingredients'],
        cuisine: 'italian',
        source: { name: 'Mob Kitchen', url: 'https://www.mob.co.uk/recipes/cacio-e-pepe' },
        favourite: false,
        timesCooked: 0,
        description: 'Just pasta, pecorino and black pepper. Three ingredients, pure comfort, and zero leftovers.',
        dietary: ['vegetarian'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'None',
        prepTime: 3,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-garlic-prawn-linguine',
        name: 'Garlic Prawn Linguine',
        image: '',
        cookTime: 15,
        calories: 480,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'quick', 'under-20-min', 'pescatarian', 'date-night'],
        cuisine: 'italian',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/garlic-prawn-linguine' },
        favourite: false,
        timesCooked: 0,
        description: 'King prawns tossed in garlic, chilli and lemon with linguine. Feels fancy, takes 15 minutes.',
        dietary: ['pescatarian'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Prawns',
        prepTime: 5,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-one-pot-pasta',
        name: 'One-Pot Tomato & Basil Pasta',
        image: '',
        cookTime: 15,
        calories: 400,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'one-pot', 'quick', 'vegan', 'budget-friendly'],
        cuisine: 'italian',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/one-pot-pasta' },
        favourite: false,
        timesCooked: 0,
        description: 'Everything cooks in one pan \u2014 pasta, tomatoes, garlic, basil. Almost no washing up.',
        dietary: ['vegan', 'vegetarian', 'dairy-free'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'None',
        prepTime: 5,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-pesto-gnocchi',
        name: 'Crispy Pesto Gnocchi',
        image: '',
        cookTime: 10,
        calories: 420,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'quick', 'under-20-min', 'vegetarian'],
        cuisine: 'italian',
        source: { name: 'Mob Kitchen', url: 'https://www.mob.co.uk/recipes/crispy-pesto-gnocchi' },
        favourite: false,
        timesCooked: 0,
        description: 'Shop-bought gnocchi pan-fried until crispy, tossed in pesto with cherry tomatoes and spinach. Stupid easy.',
        dietary: ['vegetarian'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'None',
        prepTime: 2,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-carbonara',
        name: 'Spaghetti Carbonara for One',
        image: '',
        cookTime: 15,
        calories: 550,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'quick', 'comfort-food'],
        cuisine: 'italian',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/ultimate-spaghetti-carbonara' },
        favourite: false,
        timesCooked: 0,
        description: 'The real deal \u2014 egg, pecorino, guanciale (or bacon) and black pepper. No cream.',
        dietary: [],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Bacon',
        prepTime: 5,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-salmon-teriyaki',
        name: 'Teriyaki Salmon with Noodles',
        image: '',
        cookTime: 15,
        calories: 520,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'quick', 'pescatarian', 'one-pan'],
        cuisine: 'japanese',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/teriyaki-salmon-noodles' },
        favourite: false,
        timesCooked: 0,
        description: 'Glazed salmon fillet with egg noodles and stir-fried veg. A solo treat that looks like a restaurant plate.',
        dietary: ['pescatarian', 'dairy-free'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Salmon',
        prepTime: 5,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-fish-finger-sandwich',
        name: 'Posh Fish Finger Sandwich',
        image: '',
        cookTime: 15,
        calories: 450,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'quick', 'comfort-food', 'pescatarian'],
        cuisine: 'british',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/posh-fish-finger-sandwich' },
        favourite: false,
        timesCooked: 0,
        description: 'Crispy battered fish fingers in a ciabatta roll with tartare sauce and rocket. Nostalgia, elevated.',
        dietary: ['pescatarian'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Fish',
        prepTime: 5,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-tuna-pasta-bake',
        name: 'Tuna Pasta Bake for One',
        image: '',
        cookTime: 25,
        calories: 520,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'comfort-food', 'budget-friendly', 'pescatarian'],
        cuisine: 'british',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/tuna-pasta-bake' },
        favourite: false,
        timesCooked: 0,
        description: 'Creamy tuna pasta bake with sweetcorn and cheese topping. Budget-friendly and deeply satisfying.',
        dietary: ['pescatarian'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Tuna',
        prepTime: 10,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-prawn-fried-rice',
        name: 'Prawn Fried Rice',
        image: '',
        cookTime: 10,
        calories: 400,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'quick', 'under-20-min', 'use-up-leftovers', 'pescatarian'],
        cuisine: 'chinese',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/prawn-fried-rice' },
        favourite: false,
        timesCooked: 0,
        description: 'The ultimate leftover rice recipe. Frozen prawns, egg, soy sauce, and whatever veg you have.',
        dietary: ['pescatarian', 'dairy-free'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Prawns',
        prepTime: 5,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-smoked-mackerel-salad',
        name: 'Smoked Mackerel & Beetroot Salad',
        image: '',
        cookTime: 0,
        calories: 380,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'quick', 'no-cook', 'pescatarian', 'high-protein', 'healthy'],
        cuisine: 'british',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/smoked-mackerel-beetroot-salad' },
        favourite: false,
        timesCooked: 0,
        description: 'No cooking required. Flaked smoked mackerel with beetroot, horseradish and watercress.',
        dietary: ['pescatarian', 'gluten-free'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Mackerel',
        prepTime: 10,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-mushroom-risotto',
        name: 'Mushroom Risotto for One',
        image: '',
        cookTime: 25,
        calories: 450,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'vegetarian', 'comfort-food', 'one-pot'],
        cuisine: 'italian',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/mushroom-risotto' },
        favourite: false,
        timesCooked: 0,
        description: 'Creamy risotto with chestnut mushrooms and Parmesan. Meditative stirring, solo dinner bliss.',
        dietary: ['vegetarian'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'None',
        prepTime: 5,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-halloumi-wrap',
        name: 'Grilled Halloumi & Veg Wrap',
        image: '',
        cookTime: 10,
        calories: 480,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'quick', 'under-20-min', 'vegetarian'],
        cuisine: 'mediterranean',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/halloumi-wrap' },
        favourite: false,
        timesCooked: 0,
        description: 'Griddled halloumi with roasted peppers, rocket and hummus in a warm tortilla. Done in 15 minutes.',
        dietary: ['vegetarian'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Halloumi',
        prepTime: 5,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-egg-fried-rice',
        name: 'Veggie Egg Fried Rice',
        image: '',
        cookTime: 10,
        calories: 380,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'quick', 'under-20-min', 'vegetarian', 'budget-friendly', 'use-up-leftovers'],
        cuisine: 'chinese',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/egg-fried-rice' },
        favourite: false,
        timesCooked: 0,
        description: 'Leftover rice, an egg, soy sauce, frozen peas. The solo cook\'s best friend.',
        dietary: ['vegetarian', 'dairy-free'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Egg',
        prepTime: 5,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-shakshuka',
        name: 'Shakshuka for One',
        image: '',
        cookTime: 20,
        calories: 320,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'vegetarian', 'one-pan', 'budget-friendly'],
        cuisine: 'middle eastern',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/shakshuka' },
        favourite: false,
        timesCooked: 0,
        description: 'Eggs baked in a spiced tomato sauce with cumin and paprika. Scoop it up with crusty bread.',
        dietary: ['vegetarian', 'gluten-free'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Egg',
        prepTime: 5,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-loaded-sweet-potato',
        name: 'Loaded Sweet Potato',
        image: '',
        cookTime: 45,
        calories: 420,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'vegetarian', 'budget-friendly', 'healthy'],
        cuisine: 'british',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/loaded-sweet-potato' },
        favourite: false,
        timesCooked: 0,
        description: 'Baked sweet potato loaded with black beans, cheese, avocado and sour cream. Low effort, high reward.',
        dietary: ['vegetarian', 'gluten-free'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'None',
        prepTime: 5,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-peanut-noodles',
        name: 'Peanut Butter Noodles',
        image: '',
        cookTime: 10,
        calories: 450,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'quick', 'under-20-min', 'vegan', 'budget-friendly'],
        cuisine: 'asian-fusion',
        source: { name: 'Mob Kitchen', url: 'https://www.mob.co.uk/recipes/peanut-butter-noodles' },
        favourite: false,
        timesCooked: 0,
        description: 'Noodles in a 5-minute peanut butter, soy and sriracha sauce. Dangerously addictive solo dinner.',
        dietary: ['vegan', 'vegetarian', 'dairy-free'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'None',
        prepTime: 5,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-dal-rice',
        name: 'Quick Dal with Rice',
        image: '',
        cookTime: 20,
        calories: 380,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'vegan', 'budget-friendly', 'one-pot', 'high-protein'],
        cuisine: 'indian',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/quick-dal' },
        favourite: false,
        timesCooked: 0,
        description: 'Red lentil dal with cumin, turmeric and garlic. Cheap, filling, and freezes perfectly for future solo dinners.',
        dietary: ['vegan', 'vegetarian', 'dairy-free', 'gluten-free'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Lentils',
        prepTime: 5,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-tofu-stir-fry',
        name: 'Crispy Tofu Stir-Fry',
        image: '',
        cookTime: 15,
        calories: 400,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'vegan', 'quick', 'high-protein'],
        cuisine: 'chinese',
        source: { name: 'Mob Kitchen', url: 'https://www.mob.co.uk/recipes/crispy-tofu-stir-fry' },
        favourite: false,
        timesCooked: 0,
        description: 'Cornflour-coated tofu pan-fried until crispy, with stir-fried veg and sweet chilli sauce.',
        dietary: ['vegan', 'vegetarian', 'dairy-free'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Tofu',
        prepTime: 10,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-steak-chips',
        name: 'Steak & Chips for One',
        image: '',
        cookTime: 25,
        calories: 600,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'treat-yourself', 'date-night'],
        cuisine: 'british',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/steak-chips' },
        favourite: false,
        timesCooked: 0,
        description: 'A sirloin steak cooked exactly how you like it, with oven chips and peppercorn sauce. Solo luxury.',
        dietary: ['gluten-free'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Beef',
        prepTime: 10,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-burger',
        name: 'Homemade Smash Burger',
        image: '',
        cookTime: 10,
        calories: 550,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'quick', 'under-20-min', 'fakeaway'],
        cuisine: 'american',
        source: { name: 'Mob Kitchen', url: 'https://www.mob.co.uk/recipes/smash-burger' },
        favourite: false,
        timesCooked: 0,
        description: 'Thin beef patties smashed on a screaming hot pan with American cheese and pickles. Fakeaway perfection.',
        dietary: [],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Beef',
        prepTime: 5,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-pork-chop',
        name: 'Pan-Fried Pork Chop with Apple',
        image: '',
        cookTime: 15,
        calories: 450,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'quick', 'under-20-min'],
        cuisine: 'british',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/pan-fried-pork-chop-apple' },
        favourite: false,
        timesCooked: 0,
        description: 'A golden pork chop with a quick apple and mustard pan sauce. Classic solo weeknight dinner.',
        dietary: ['gluten-free'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Pork',
        prepTime: 5,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-lamb-chop-salad',
        name: 'Lamb Chop with Grain Salad',
        image: '',
        cookTime: 15,
        calories: 500,
        servings: 1,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'quick', 'healthy', 'high-protein'],
        cuisine: 'mediterranean',
        source: { name: 'Olive Magazine', url: 'https://www.olivemagazine.com/recipes/quick-and-easy/lamb-chops-grain-salad/' },
        favourite: false,
        timesCooked: 0,
        description: 'Quick-grilled lamb chops with a warm grain and herb salad. Restaurant-quality solo dinner.',
        dietary: [],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Lamb',
        prepTime: 10,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-bolognese',
        name: 'Solo Bolognese (Freezer-Friendly)',
        image: '',
        cookTime: 30,
        calories: 520,
        servings: 2,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'batch-cook', 'freezer-friendly', 'comfort-food'],
        cuisine: 'italian',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/best-spaghetti-bolognese' },
        favourite: false,
        timesCooked: 0,
        description: 'Makes 2 portions \u2014 eat one tonight, freeze the other. The solo cook\'s batch cooking staple.',
        dietary: [],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Beef',
        prepTime: 10,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-chicken-curry',
        name: 'Easy Chicken Curry (Batch)',
        image: '',
        cookTime: 25,
        calories: 480,
        servings: 2,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'batch-cook', 'freezer-friendly', 'fakeaway'],
        cuisine: 'indian',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/easy-chicken-curry' },
        favourite: false,
        timesCooked: 0,
        description: 'A creamy, mild chicken curry that makes 2 portions. Tonight\'s dinner and tomorrow\'s lunch sorted.',
        dietary: ['gluten-free'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Chicken',
        prepTime: 10,
        tips: '',
        ingredients: [],
        steps: [],
    },
    {
        id: 'solo-chilli-batch',
        name: 'Turkey Chilli (Freeze & Reheat)',
        image: '',
        cookTime: 30,
        calories: 380,
        servings: 2,
        difficulty: 'Easy',
        tags: ['solo-friendly', 'batch-cook', 'freezer-friendly', 'budget-friendly', 'high-protein'],
        cuisine: 'mexican',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/turkey-chilli' },
        favourite: false,
        timesCooked: 0,
        description: 'Lean turkey mince chilli that freezes brilliantly. Lower fat than beef, just as satisfying.',
        dietary: ['dairy-free', 'gluten-free'],
        soloFriendly: true,
        familyFriendly: false,
        mainProtein: 'Turkey',
        prepTime: 10,
        tips: '',
        ingredients: [],
        steps: [],
    },
);
