// ===========================================
// MEAL PLANNER v3 — Recipe Data
// ===========================================

const recipes = [
    {
        id: 'thai-green-curry', name: 'Thai Green Curry',
        image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&h=400&fit=crop',
        cookTime: 25, calories: 380, servings: 4, difficulty: 'Easy',
        tags: ['Asian', 'Curry', 'Healthy'], cuisine: 'asian',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/thai-green-curry' },
        favourite: true, timesCooked: 5,
        ingredients: [
            { name: 'Chicken breast', amount: 400, unit: 'g', category: 'protein' },
            { name: 'Red pepper', amount: 1, unit: '', category: 'vegetables', prep: 'sliced' },
            { name: 'Courgette', amount: 1, unit: '', category: 'vegetables', prep: 'sliced' },
            { name: 'Green beans', amount: 100, unit: 'g', category: 'vegetables' },
            { name: 'Thai green curry paste', amount: 3, unit: 'tbsp', category: 'sauce' },
            { name: 'Coconut milk', amount: 400, unit: 'ml', category: 'sauce' },
            { name: 'Jasmine rice', amount: 300, unit: 'g', category: 'carbs' },
            { name: 'Fish sauce', amount: 1, unit: 'tbsp', category: 'sauce' },
            { name: 'Lime', amount: 1, unit: '', category: 'vegetables' },
        ],
        steps: [
            { text: 'Cook jasmine rice according to packet instructions.', time: 12 },
            { text: 'Slice the chicken breast into strips. Slice the pepper and courgette.', time: 5 },
            { text: 'Heat oil in a wok over high heat. Fry chicken until golden.', time: 4 },
            { text: 'Add curry paste and stir for 1 minute until fragrant.', time: 1 },
            { text: 'Pour in coconut milk and add vegetables. Simmer until cooked through.', time: 8 },
            { text: 'Season with fish sauce and a squeeze of lime. Serve over rice.' },
        ]
    },
    {
        id: 'fish-and-chips', name: 'Beer Battered Fish & Chips',
        image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&h=400&fit=crop',
        cookTime: 30, calories: 850, servings: 2, difficulty: 'Medium',
        tags: ['British', 'Fish', 'Classic'], cuisine: 'british',
        source: { name: 'Gluten Free Cuppa Tea', url: '#' },
        favourite: false, timesCooked: 2,
        ingredients: [
            { name: 'Cod fillets', amount: 2, unit: '', category: 'protein' },
            { name: 'Self-raising flour', amount: 175, unit: 'g', category: 'carbs' },
            { name: 'Beer', amount: 275, unit: 'ml', category: 'sauce' },
            { name: 'Potatoes', amount: 4, unit: 'large', category: 'carbs', prep: 'chipped' },
            { name: 'Vegetable oil', amount: 500, unit: 'ml', category: 'pantry' },
            { name: 'Salt', amount: 1, unit: 'tsp', category: 'pantry' },
            { name: 'Lemon', amount: 1, unit: '', category: 'vegetables' },
        ],
        steps: [
            { text: 'Cut potatoes into chips. Parboil for 5 minutes, then drain and pat dry.', time: 8 },
            { text: 'Mix flour and salt. Gradually whisk in the beer to make a smooth batter.' },
            { text: 'Heat oil to 180°C in a deep pan or fryer.', time: 5 },
            { text: 'Pat fish dry. Dust with flour, then dip into batter.' },
            { text: 'Carefully lower fish into hot oil. Fry until golden and crisp.', time: 8 },
            { text: 'Fry chips until golden. Drain everything on kitchen paper.', time: 5 },
            { text: 'Serve with lemon wedges and mushy peas.' },
        ]
    },
    {
        id: 'five-bean-chilli', name: 'Five-Bean Chilli',
        image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&h=400&fit=crop',
        cookTime: 30, calories: 450, servings: 4, difficulty: 'Easy',
        tags: ['Mexican', 'Vegetarian', 'Healthy', 'Vegan'], cuisine: 'mexican',
        source: { name: 'BBC Good Food', url: '#' },
        favourite: true, timesCooked: 8,
        ingredients: [
            { name: 'Olive oil', amount: 1, unit: 'tbsp', category: 'pantry' },
            { name: 'Onion', amount: 1, unit: '', category: 'vegetables', prep: 'chopped' },
            { name: 'Garlic cloves', amount: 2, unit: '', category: 'vegetables', prep: 'crushed' },
            { name: 'Red pepper', amount: 1, unit: '', category: 'vegetables', prep: 'diced' },
            { name: 'Chopped tomatoes', amount: 400, unit: 'g tin', category: 'sauce' },
            { name: 'Kidney beans', amount: 400, unit: 'g tin', category: 'protein' },
            { name: 'Black beans', amount: 400, unit: 'g tin', category: 'protein' },
            { name: 'Cannellini beans', amount: 400, unit: 'g tin', category: 'protein' },
            { name: 'Chilli powder', amount: 1, unit: 'tsp', category: 'pantry' },
            { name: 'Ground cumin', amount: 1, unit: 'tsp', category: 'pantry' },
            { name: 'Rice', amount: 200, unit: 'g', category: 'carbs' },
        ],
        steps: [
            { text: 'Heat oil in a large pan over medium heat.', time: 1 },
            { text: 'Cook onion until soft and translucent.', time: 5 },
            { text: 'Add garlic and peppers, cook for 5 minutes.', time: 5 },
            { text: 'Add tomatoes, 200ml water, all beans, chilli powder and cumin. Stir well.' },
            { text: 'Bring to a simmer. Cook until sauce has thickened.', time: 20 },
            { text: 'Serve with rice and topped with soured cream and grated cheese.' },
        ]
    },
    {
        id: 'chicken-stir-fry', name: 'Chicken Stir Fry',
        image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&h=400&fit=crop',
        cookTime: 15, calories: 320, servings: 2, difficulty: 'Easy',
        tags: ['Asian', 'Quick', 'Healthy'], cuisine: 'asian',
        source: { name: 'Jamie Oliver', url: '#' },
        favourite: false, timesCooked: 0,
        ingredients: [
            { name: 'Chicken thighs', amount: 300, unit: 'g', category: 'protein', prep: 'sliced' },
            { name: 'Broccoli', amount: 200, unit: 'g', category: 'vegetables', prep: 'florets' },
            { name: 'Pak choi', amount: 2, unit: '', category: 'vegetables' },
            { name: 'Soy sauce', amount: 2, unit: 'tbsp', category: 'pantry' },
            { name: 'Sesame oil', amount: 1, unit: 'tsp', category: 'pantry' },
            { name: 'Ginger', amount: 1, unit: 'thumb', category: 'vegetables', prep: 'grated' },
            { name: 'Egg noodles', amount: 200, unit: 'g', category: 'carbs' },
        ],
        steps: [
            { text: 'Cook noodles according to packet instructions. Drain and set aside.', time: 4 },
            { text: 'Heat sesame oil in a wok over high heat.' },
            { text: 'Add chicken and stir-fry until golden.', time: 4 },
            { text: 'Add broccoli and ginger. Toss for 2 minutes.', time: 2 },
            { text: 'Add pak choi and soy sauce. Cook until wilted.', time: 2 },
            { text: 'Toss in noodles and serve immediately.' },
        ]
    },
    {
        id: 'spaghetti-bolognese', name: 'Spaghetti Bolognese',
        image: 'https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?w=600&h=400&fit=crop',
        cookTime: 40, calories: 520, servings: 4, difficulty: 'Easy',
        tags: ['Italian', 'Classic', 'Family'], cuisine: 'italian',
        source: { name: 'BBC Good Food', url: '#' },
        favourite: true, timesCooked: 12,
        ingredients: [
            { name: 'Beef mince', amount: 500, unit: 'g', category: 'protein' },
            { name: 'Onion', amount: 1, unit: '', category: 'vegetables', prep: 'diced' },
            { name: 'Carrot', amount: 1, unit: '', category: 'vegetables', prep: 'diced' },
            { name: 'Celery stick', amount: 1, unit: '', category: 'vegetables', prep: 'diced' },
            { name: 'Garlic cloves', amount: 2, unit: '', category: 'vegetables', prep: 'crushed' },
            { name: 'Chopped tomatoes', amount: 400, unit: 'g tin', category: 'sauce' },
            { name: 'Tomato puree', amount: 2, unit: 'tbsp', category: 'sauce' },
            { name: 'Spaghetti', amount: 300, unit: 'g', category: 'carbs' },
            { name: 'Parmesan', amount: 50, unit: 'g', category: 'sauce' },
            { name: 'Olive oil', amount: 1, unit: 'tbsp', category: 'pantry' },
        ],
        steps: [
            { text: 'Heat olive oil in a large pan. Cook onion, carrot and celery until softened.', time: 8 },
            { text: 'Add garlic and cook for 1 minute.', time: 1 },
            { text: 'Turn up the heat. Add mince and cook until browned, breaking it up.', time: 5 },
            { text: 'Add tomatoes, tomato puree and 100ml water. Season well.' },
            { text: 'Bring to a simmer. Cook on low heat until rich and thick.', time: 25 },
            { text: 'Meanwhile, cook spaghetti according to packet instructions.', time: 10 },
            { text: 'Serve bolognese over spaghetti. Top with grated parmesan.' },
        ]
    },
    {
        id: 'salmon-teriyaki', name: 'Salmon Teriyaki Bowl',
        image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop',
        cookTime: 20, calories: 480, servings: 2, difficulty: 'Easy',
        tags: ['Asian', 'Fish', 'Healthy', 'Quick'], cuisine: 'asian',
        source: { name: 'Delicious Magazine', url: '#' },
        favourite: false, timesCooked: 1,
        ingredients: [
            { name: 'Salmon fillets', amount: 2, unit: '', category: 'protein' },
            { name: 'Soy sauce', amount: 3, unit: 'tbsp', category: 'pantry' },
            { name: 'Mirin', amount: 2, unit: 'tbsp', category: 'sauce' },
            { name: 'Honey', amount: 1, unit: 'tbsp', category: 'pantry' },
            { name: 'Rice', amount: 200, unit: 'g', category: 'carbs' },
            { name: 'Edamame beans', amount: 100, unit: 'g', category: 'vegetables' },
            { name: 'Avocado', amount: 1, unit: '', category: 'vegetables' },
            { name: 'Spring onions', amount: 2, unit: '', category: 'vegetables', prep: 'sliced' },
            { name: 'Sesame seeds', amount: 1, unit: 'tbsp', category: 'pantry' },
        ],
        steps: [
            { text: 'Cook rice according to packet instructions.', time: 12 },
            { text: 'Mix soy sauce, mirin and honey in a small bowl.' },
            { text: 'Heat a pan over medium-high heat. Place salmon skin-side down.', time: 3 },
            { text: 'Flip salmon and pour over half the teriyaki sauce. Cook until done.', time: 4 },
            { text: 'Assemble bowls: rice, edamame, sliced avocado, salmon.' },
            { text: 'Drizzle with remaining sauce. Top with spring onions and sesame seeds.' },
        ]
    },
    {
        id: 'soy-chilli-chicken-wings', name: 'Soy & Chilli Chicken Wings',
        image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=600&h=400&fit=crop',
        cookTime: 25, calories: 520, servings: 4, difficulty: 'Easy',
        tags: ['Asian', 'Sticky', 'Sharing'], cuisine: 'asian',
        source: { name: 'BBC Good Food (inspired)', url: 'https://www.bbc.co.uk/food/recipes/' },
        favourite: false, timesCooked: 0,
        ingredients: [
            { name: 'Chicken wings', amount: 1, unit: 'kg', category: 'protein' },
            { name: 'Soy sauce', amount: 4, unit: 'tbsp', category: 'pantry' },
            { name: 'Honey', amount: 2, unit: 'tbsp', category: 'pantry' },
            { name: 'Sweet chilli sauce', amount: 2, unit: 'tbsp', category: 'sauce' },
            { name: 'Sesame oil', amount: 1, unit: 'tbsp', category: 'pantry' },
            { name: 'Rice vinegar', amount: 1, unit: 'tbsp', category: 'sauce' },
            { name: 'Garlic cloves', amount: 2, unit: '', category: 'vegetables', prep: 'minced' },
            { name: 'Ginger', amount: 1, unit: 'thumb', category: 'vegetables', prep: 'grated' },
            { name: 'Spring onions', amount: 2, unit: '', category: 'vegetables', prep: 'sliced' },
            { name: 'Red chilli', amount: 1, unit: '', category: 'vegetables', prep: 'sliced' },
            { name: 'Sesame seeds', amount: 1, unit: 'tbsp', category: 'pantry' },
        ],
        steps: [
            { text: 'Preheat oven to 200°C (180°C fan). Pat wings dry.', time: 2 },
            { text: 'Mix soy sauce, honey, sweet chilli, sesame oil, rice vinegar, garlic and ginger.', time: 3 },
            { text: 'Toss wings in marinade. Marinate for 10 minutes (or longer if time).', time: 10 },
            { text: 'Arrange wings on a lined tray. Reserve marinade for basting.', time: 2 },
            { text: 'Bake 20–25 minutes, turning halfway and basting.', time: 25 },
            { text: 'Top with spring onions, chilli and sesame seeds. Serve.', time: 2 },
        ]
    },
    {
        id: 'spaghetti-carbonara', name: 'Spaghetti Carbonara',
        image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&h=400&fit=crop',
        cookTime: 15, calories: 650, servings: 2, difficulty: 'Easy',
        tags: ['Italian', 'Classic', 'Quick'], cuisine: 'italian',
        source: { name: 'Classic recipe', url: '#' },
        favourite: false, timesCooked: 0,
        ingredients: [
            { name: 'Spaghetti', amount: 200, unit: 'g', category: 'carbs' },
            { name: 'Bacon', amount: 150, unit: 'g', category: 'protein', prep: 'chopped' },
            { name: 'Eggs', amount: 2, unit: '', category: 'protein' },
            { name: 'Parmesan', amount: 50, unit: 'g', category: 'sauce', prep: 'grated' },
            { name: 'Black pepper', amount: 1, unit: 'tsp', category: 'pantry' },
            { name: 'Salt', amount: 1, unit: 'tsp', category: 'pantry' },
        ],
        steps: [
            { text: 'Cook spaghetti in salted boiling water until al dente.', time: 10 },
            { text: 'Fry bacon until crisp.', time: 5 },
            { text: 'Beat eggs with parmesan and black pepper.', time: 2 },
            { text: 'Drain pasta, reserving a splash of water.', time: 1 },
            { text: 'Off the heat, toss pasta with bacon and egg mixture, loosening with pasta water.', time: 2 },
            { text: 'Serve immediately with extra parmesan.', time: 1 },
        ]
    },
    {
        id: 'grilled-salmon', name: 'Grilled Salmon with Lemon & Herbs',
        image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&h=400&fit=crop',
        cookTime: 15, calories: 320, servings: 2, difficulty: 'Easy',
        tags: ['Fish', 'Healthy', 'Quick'], cuisine: 'fish',
        source: { name: 'Personal Collection', url: null },
        favourite: false, timesCooked: 0,
        ingredients: [
            { name: 'Salmon fillets', amount: 2, unit: 'x 150g', category: 'protein' },
            { name: 'Lemon', amount: 1, unit: '', category: 'vegetables' },
            { name: 'Asparagus', amount: 200, unit: 'g', category: 'vegetables', prep: 'trimmed' },
            { name: 'Fresh dill', amount: 1, unit: 'small bunch', category: 'herbs' },
            { name: 'Fresh parsley', amount: 1, unit: 'small bunch', category: 'herbs' },
            { name: 'Olive oil', amount: 2, unit: 'tbsp', category: 'pantry' },
            { name: 'Salt & pepper', amount: 0, unit: 'to taste', category: 'pantry' },
        ],
        steps: [
            { text: 'Preheat grill to high. Season salmon with salt, pepper, and a drizzle of oil.' },
            { text: 'Place salmon skin-side down on a baking tray. Grill until just cooked through.', time: 10 },
            { text: 'Blanch asparagus in boiling water, then drain.', time: 3 },
            { text: 'Chop herbs finely. Serve salmon on asparagus, topped with herbs and lemon wedges.' },
        ]
    },
    {
        id: 'mushroom-risotto', name: 'Creamy Mushroom Risotto',
        image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600&h=400&fit=crop',
        cookTime: 35, calories: 420, servings: 4, difficulty: 'Medium',
        tags: ['Italian', 'Vegetarian', 'Comfort'], cuisine: 'italian',
        source: { name: 'BBC Good Food', url: 'https://www.bbcgoodfood.com/recipes/mushroom-risotto' },
        favourite: true, timesCooked: 7,
        ingredients: [
            { name: 'Mixed mushrooms', amount: 300, unit: 'g', category: 'vegetables', prep: 'sliced' },
            { name: 'Onion', amount: 1, unit: 'medium', category: 'vegetables', prep: 'finely diced' },
            { name: 'Garlic cloves', amount: 2, unit: '', category: 'vegetables', prep: 'minced' },
            { name: 'Arborio rice', amount: 300, unit: 'g', category: 'carbs' },
            { name: 'Parmesan', amount: 60, unit: 'g', category: 'dairy', prep: 'grated' },
            { name: 'Butter', amount: 30, unit: 'g', category: 'dairy' },
            { name: 'Vegetable stock', amount: 1, unit: 'litre', category: 'liquid', prep: 'kept warm' },
            { name: 'White wine', amount: 150, unit: 'ml', category: 'liquid' },
            { name: 'Olive oil', amount: 2, unit: 'tbsp', category: 'pantry' },
            { name: 'Fresh thyme', amount: 1, unit: 'few sprigs', category: 'herbs' },
        ],
        steps: [
            { text: 'Heat oil and half the butter. Fry mushrooms until golden; set aside.', time: 8 },
            { text: 'Sauté onion until soft. Add garlic and rice, stir for 1 minute.', time: 5 },
            { text: 'Pour in wine and stir until absorbed.', time: 2 },
            { text: 'Add stock a ladleful at a time, stirring until absorbed.', time: 18 },
            { text: 'Stir in mushrooms, remaining butter, and parmesan. Season and serve.' },
        ]
    },
    {
        id: 'fish-tacos', name: 'Crispy Fish Tacos',
        image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600&h=400&fit=crop',
        cookTime: 25, calories: 350, servings: 4, difficulty: 'Easy',
        tags: ['Fish', 'Mexican', 'Quick'], cuisine: 'fish',
        source: { name: 'Family Recipe', url: null },
        favourite: false, timesCooked: 2,
        ingredients: [
            { name: 'White fish fillets', amount: 400, unit: 'g', category: 'protein', prep: 'cod or haddock' },
            { name: 'Red cabbage', amount: 150, unit: 'g', category: 'vegetables', prep: 'finely shredded' },
            { name: 'Lime', amount: 2, unit: '', category: 'vegetables' },
            { name: 'Fresh coriander', amount: 1, unit: 'bunch', category: 'herbs' },
            { name: 'Small flour tortillas', amount: 8, unit: '', category: 'carbs' },
            { name: 'Mayonnaise', amount: 100, unit: 'g', category: 'sauce' },
            { name: 'Chipotle paste', amount: 1, unit: 'tbsp', category: 'sauce' },
            { name: 'Plain flour', amount: 50, unit: 'g', category: 'pantry' },
            { name: 'Paprika', amount: 1, unit: 'tsp', category: 'pantry' },
            { name: 'Vegetable oil', amount: 0, unit: 'for frying', category: 'pantry' },
        ],
        steps: [
            { text: 'Mix flour with paprika and seasoning. Coat fish pieces in the mixture.' },
            { text: 'Shallow fry fish until golden and cooked through. Drain on kitchen paper.', time: 8 },
            { text: 'Mix mayo with chipotle paste and lime juice to make the sauce.' },
            { text: 'Warm tortillas in a dry pan.', time: 2 },
            { text: 'Assemble tacos with fish, cabbage, chipotle mayo, and coriander.' },
        ]
    },
    {
        id: 'veggie-stir-fry', name: 'Quick Veggie Stir-Fry',
        image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&h=400&fit=crop',
        cookTime: 15, calories: 280, servings: 2, difficulty: 'Easy',
        tags: ['Vegetarian', 'Asian', 'Quick', 'Healthy'], cuisine: 'vegetarian',
        source: { name: 'Personal Collection', url: null },
        favourite: false, timesCooked: 8,
        ingredients: [
            { name: 'Broccoli', amount: 150, unit: 'g', category: 'vegetables', prep: 'cut into florets' },
            { name: 'Pak choi', amount: 2, unit: 'heads', category: 'vegetables', prep: 'quartered' },
            { name: 'Red pepper', amount: 1, unit: '', category: 'vegetables', prep: 'sliced' },
            { name: 'Carrot', amount: 1, unit: 'large', category: 'vegetables', prep: 'julienned' },
            { name: 'Spring onions', amount: 4, unit: '', category: 'vegetables', prep: 'sliced' },
            { name: 'Soy sauce', amount: 2, unit: 'tbsp', category: 'sauce' },
            { name: 'Sesame oil', amount: 1, unit: 'tsp', category: 'pantry' },
            { name: 'Rice vinegar', amount: 1, unit: 'tbsp', category: 'sauce' },
            { name: 'Vegetable oil', amount: 1, unit: 'tbsp', category: 'pantry' },
            { name: 'Garlic', amount: 2, unit: 'cloves', category: 'pantry', prep: 'minced' },
            { name: 'Fresh ginger', amount: 1, unit: 'inch piece', category: 'pantry', prep: 'grated' },
        ],
        steps: [
            { text: 'Mix soy sauce, sesame oil, and rice vinegar in a small bowl.' },
            { text: 'Heat oil in a wok. Add garlic and ginger, stir for 30 seconds.', time: 1 },
            { text: 'Add broccoli and carrot first. Stir-fry for 2–3 minutes.', time: 3 },
            { text: 'Add remaining vegetables. Stir-fry until tender-crisp.', time: 3 },
            { text: 'Pour over sauce, toss well, and serve with rice or noodles.' },
        ]
    },
    {
        id: 'beef-teriyaki', name: 'Beef Teriyaki Bowl',
        image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop',
        cookTime: 20, calories: 450, servings: 2, difficulty: 'Easy',
        tags: ['Asian', 'Quick', 'Beef'], cuisine: 'asian',
        source: { name: 'Family Recipe', url: null },
        favourite: true, timesCooked: 6,
        ingredients: [
            { name: 'Sirloin steak', amount: 300, unit: 'g', category: 'protein', prep: 'thinly sliced' },
            { name: 'Broccoli', amount: 150, unit: 'g', category: 'vegetables', prep: 'florets' },
            { name: 'Edamame beans', amount: 100, unit: 'g', category: 'vegetables' },
            { name: 'Spring onions', amount: 3, unit: '', category: 'vegetables', prep: 'sliced' },
            { name: 'Sushi rice', amount: 200, unit: 'g', category: 'carbs' },
            { name: 'Soy sauce', amount: 3, unit: 'tbsp', category: 'sauce' },
            { name: 'Mirin', amount: 2, unit: 'tbsp', category: 'sauce' },
            { name: 'Brown sugar', amount: 1, unit: 'tbsp', category: 'sauce' },
            { name: 'Sesame seeds', amount: 1, unit: 'tbsp', category: 'pantry' },
            { name: 'Vegetable oil', amount: 1, unit: 'tbsp', category: 'pantry' },
        ],
        steps: [
            { text: 'Cook rice according to packet instructions.', time: 12 },
            { text: 'Mix soy sauce, mirin, and sugar to make teriyaki sauce.' },
            { text: 'Steam broccoli and edamame until just tender.', time: 5 },
            { text: 'Flash-fry beef slices over high heat.', time: 2 },
            { text: 'Add sauce to beef, coat well. Serve over rice with vegetables and spring onions.', time: 2 },
        ]
    }
];
